import { db } from "@/lib/db";
import { env } from "@/lib/env";
import { createApprovalToken } from "@/lib/autopilotApproval";

type QueueEntry = {
  queueId: string;
  triageItemId: string;
  title: string;
  summary: string;
  severity: "low" | "medium" | "high" | "critical";
  riskClass: "low" | "medium" | "high";
  proposal: {
    plainLanguageFix: string;
    nextActions: string[];
  };
};

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function decisionUrl(baseUrl: string, queueId: string, decision: "approve" | "reject", draft: boolean) {
  const exp = Math.floor(Date.now() / 1000) + 60 * 60 * 48;
  const signature = createApprovalToken({ queueId, decision, exp, draft });
  const url = new URL("/api/internal/autopilot/decision", baseUrl);
  url.searchParams.set("queueId", queueId);
  url.searchParams.set("decision", decision);
  url.searchParams.set("exp", String(exp));
  url.searchParams.set("sig", signature);
  url.searchParams.set("draft", draft ? "1" : "0");
  return url.toString();
}

export function autopilotApprovalEmailConfigured() {
  return Boolean(env.RESEND_API_KEY && env.TRIAGE_EMAIL_TO && env.TRIAGE_EMAIL_FROM && env.NEXT_PUBLIC_SITE_URL);
}

export async function sendAutopilotApprovalEmail(
  entries: QueueEntry[],
  options: { actorType: "system" | "admin"; actorId?: string | null }
) {
  if (!entries.length) return { sent: false, reason: "No autopilot queue entries to notify" } as const;
  if (!autopilotApprovalEmailConfigured()) return { sent: false, reason: "Approval email is not configured" } as const;

  const baseUrl = env.NEXT_PUBLIC_SITE_URL;
  const itemsHtml = entries
    .map((entry, index) => {
      const approveUrl = decisionUrl(baseUrl, entry.queueId, "approve", true);
      const rejectUrl = decisionUrl(baseUrl, entry.queueId, "reject", false);
      const actions = entry.proposal.nextActions.length
        ? `<ol>${entry.proposal.nextActions.map((step) => `<li>${escapeHtml(step)}</li>`).join("")}</ol>`
        : "<p>No concrete steps generated.</p>";
      return `
        <div style="padding:12px;border:1px solid #e5e7eb;border-radius:8px;margin-bottom:12px;">
          <p style="margin:0 0 4px 0;font-size:12px;color:#6b7280;">Item ${index + 1} • severity ${entry.severity} • risk ${entry.riskClass}</p>
          <h3 style="margin:0 0 8px 0;">${escapeHtml(entry.title)}</h3>
          <p style="margin:0 0 8px 0;">${escapeHtml(entry.summary)}</p>
          <p style="margin:0 0 8px 0;"><strong>Proposed fix:</strong> ${escapeHtml(entry.proposal.plainLanguageFix || "No recommendation provided")}</p>
          ${actions}
          <p style="margin-top:10px;">
            <a href="${approveUrl}" style="display:inline-block;margin-right:10px;padding:8px 12px;background:#16a34a;color:#fff;border-radius:6px;text-decoration:none;">Approve + Create Draft</a>
            <a href="${rejectUrl}" style="display:inline-block;padding:8px 12px;background:#dc2626;color:#fff;border-radius:6px;text-decoration:none;">Reject</a>
          </p>
        </div>
      `;
    })
    .join("");

  const html = `
    <div style="font-family:Arial,sans-serif;max-width:760px;margin:0 auto;color:#111827;">
      <h2 style="margin-bottom:6px;">Autopilot triage approvals needed</h2>
      <p style="margin-top:0;color:#4b5563;">Review each proposal and approve/reject directly from this email. Approval links expire in 48 hours.</p>
      ${itemsHtml}
      <p style="font-size:12px;color:#6b7280;">Generated by the WineApp autopilot queue.</p>
    </div>
  `;

  const textItems = entries
    .map((entry, index) => {
      const approveUrl = decisionUrl(baseUrl, entry.queueId, "approve", true);
      const rejectUrl = decisionUrl(baseUrl, entry.queueId, "reject", false);
      const steps = entry.proposal.nextActions.length
        ? entry.proposal.nextActions.map((step, i) => `    ${i + 1}. ${step}`).join("\n")
        : "    1. No concrete steps generated.";
      return [
        `${index + 1}) ${entry.title}`,
        `   severity=${entry.severity}, risk=${entry.riskClass}`,
        `   summary: ${entry.summary}`,
        `   proposed fix: ${entry.proposal.plainLanguageFix || "No recommendation provided"}`,
        "   next actions:",
        steps,
        `   approve + draft: ${approveUrl}`,
        `   reject: ${rejectUrl}`
      ].join("\n");
    })
    .join("\n\n");

  const subject = `[WineApp] ${entries.length} triage item(s) need approval`;
  const text = [`Autopilot triage approvals needed (${entries.length})`, "", textItems].join("\n");

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${env.RESEND_API_KEY as string}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      from: env.TRIAGE_EMAIL_FROM,
      to: [env.TRIAGE_EMAIL_TO],
      subject,
      html,
      text
    }),
    cache: "no-store"
  });

  if (!res.ok) {
    const bodyText = (await res.text()).slice(0, 280);
    throw new Error(`Email provider rejected approval send (status ${res.status}): ${bodyText || "no details"}`);
  }

  const body = (await res.json()) as { id?: string };

  await db.from("audit_logs").insert({
    actor_type: options.actorType,
    actor_id: options.actorId || null,
    action: "triage_autopilot_approval_email_sent",
    target_type: "triage_autopilot_queue",
    target_id: null,
    metadata: {
      queue_count: entries.length,
      provider: "resend",
      provider_message_id: body.id || null
    }
  });

  return {
    sent: true,
    queueCount: entries.length,
    providerMessageId: body.id || null
  } as const;
}

